name: simple-file-storage

services:
    # https://hub.docker.com/_/mariadb
    mariadb:
        image: mariadb:12
        restart: always
        volumes:
            - ./docker/services/database:/var/lib/mysql
        command: [ "--collation-server=utf8mb4_unicode_ci" ]
        environment:
            TZ: ${TZ}
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_PORT: ${DATABASE_PORT}
            MARIADB_USER: ${DATABASE_USERNAME}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_AUTO_UPGRADE: true
            MARIADB_INITDB_SKIP_TZINFO: true
            MARIADB_RANDOM_ROOT_PASSWORD: true
        healthcheck:
            test: healthcheck.sh --su-mysql --connect --innodb_initialized
            retries: 3
            timeout: 5s
        expose:
            - "${DATABASE_PORT}"

    # https://hub.docker.com/_/phpmyadmin
    phpmyadmin:
        image: phpmyadmin:5-apache
        restart: always
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            PMA_HOST: ${DATABASE_HOST}
            PMA_PORT: ${DATABASE_PORT}
            PMA_USER: ${DATABASE_USERNAME}
            APACHE_PORT: 8080
            PMA_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test: curl -f http://localhost:8080/
            retries: 3
            timeout: 5s
        expose:
            - "8080"

    # https://hub.docker.com/_/varnish
    varnish:
        image: varnish:8-alpine
        volumes:
            - ./docker/configuration/default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            node:
                condition: service_healthy
        environment:
            VARNISH_SIZE: 128m
        healthcheck:
            test: wget -O - http://localhost/
            retries: 3
            timeout: 5s

    # https://github.com/FlorianLeChat/Simple-File-Storage
    node:
        image: simple-file-storage
        restart: always
        command: ./docker/scripts/entrypoint.sh
        volumes:
            - ./logs:/usr/src/app/logs
            - ./public/files:/usr/src/app/public/files
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            TZ: ${TZ}
        healthcheck:
            test: wget -O - http://localhost:3000/
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./docker/scripts/Dockerfile
        expose:
            - "3000"