name: simple-file-storage

services:
    database:
        image: mariadb:12
        restart: unless-stopped
        volumes:
            - mariadb_data:/var/lib/mysql
        command: --collation-server=utf8mb4_unicode_ci
        environment:
            TZ: ${TZ}
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USERNAME}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
            MARIADB_AUTO_UPGRADE: true
            MARIADB_INITDB_SKIP_TZINFO: true
            MARIADB_RANDOM_ROOT_PASSWORD: true
        healthcheck:
            test: healthcheck.sh --su-mysql --connect --innodb_initialized
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 64
                    cpus: "0.5"
                    memory: 256M

    proxy:
        image: varnish:8-alpine
        restart: unless-stopped
        volumes:
            - ./docker/configuration/varnish.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            server:
                condition: service_healthy
        environment:
            VARNISH_SIZE: 128m
        healthcheck:
            test: wget -O - http://localhost/
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 1024
                    cpus: "0.5"
                    memory: 256M
        ports:
            - "${PORT:-80}:80"

    server:
        user: "${UID:-1000}:${GID:-1000}"
        image: registry.florian-dev.fr/floriantrayon/simple-file-storage:${VERSION:-latest}
        restart: unless-stopped
        command: bash -c "npm run db:migrate || true; npm run start"
        volumes:
            - ./logs:/usr/src/app/logs
            - ./public/files:/usr/src/app/public/files
        env_file:
            - .env
        depends_on:
            database:
                condition: service_healthy
        security_opt:
            - no-new-privileges=true
        healthcheck:
            test: wget -O - http://localhost:3000/
            retries: 3
            timeout: 5s
            start_period: 30s
        deploy:
            resources:
                limits:
                    pids: 64
                    cpus: "1"
                    memory: 512M
        build:
            target: production
            context: .
            dockerfile: ./docker/Dockerfile

volumes:
    mariadb_data: