framework:
    secret: "%env(APP_SECRET)%"
    http_method_override: false # par défaut à partir de Symfony 7
    handle_all_throwables: true # par défaut à partir de Symfony 7
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true
