name: Playwright Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Set npm cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
            key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
            path: ${{ steps.npm-cache.outputs.dir }}
            restore-keys: ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Switch to development mode
        run: sed -i "s/production/development/g" .env
      - name: Prepare test environment
        run: |
          sed -i 's/provider = "mysql"/provider = "sqlite"/g' prisma/schema.prisma
          sed -i 's/@db\.Text//g' prisma/schema.prisma
          sed -i 's#^DATABASE_URL=.*#DATABASE_URL="file:data.db"#' .env
          sed -i "s#AUTH_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#AUTH_SECRET=$(openssl rand -base64 32)#g" .env
          npm run migrate
          npx tsc --skipLibCheck scripts/create-fake-accounts.ts
          node scripts/create-fake-accounts.js
      - name: Build website
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test
