name: Playwright Tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Prepare test environment
        run: |
          sed -i 's/provider = "mysql"/provider = "sqlite"/g' prisma/schema.prisma
          sed -i 's/@db\.Text//g' prisma/schema.prisma
          sed -i 's#^DATABASE_URL=.*#DATABASE_URL="file:data.db?connection_limit=1"#' .env
          sed -i "s#AUTH_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#AUTH_SECRET=$(openssl rand -base64 32)#g" .env
          npx dotenv -e .env prisma migrate deploy # https://github.com/prisma/prisma/issues/10403#issuecomment-1500770484
          npm run migrate
      - name: Build website
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test
